#!/usr/bin/env python3
"""Educational-quality filter for the (multilingual) StarCoder corpus.

The cleaned/raw starcoder dump is one source file per block, tagged by language:
    <|code|>[python]            <|code|>[javascript]   <|code|>[rust]   ...
    <filename>path/to/x.py
    ...code...
    <|endcode|>
It is REAL GitHub code across many languages — functioning, but mixed quality
(autogenerated files, minified JS, data/lockfile dumps, py2-only code). For a small
from-scratch model, "no garbage" means a principled per-language gate, not volume.

LANGUAGE-AWARE:
  * python  -> HARD gate ast.parse() must succeed as valid Python 3 (the signal we
               already trust from the code executor); py2 / broken files dropped so
               the model never trains on wrong Python syntax.
  * others  -> heuristic gate (can't cheaply parse 9 languages): drop autogenerated,
               minified (huge lines), non-ascii-heavy, data-dump (no code keywords),
               too-short/too-long. Keep documented, structured, sane-formatted code.
On top, an additive 0-5 educational rubric; keep files >= threshold.

Markers are preserved in the output (so the language tag survives into pretraining).
Writes .manifest.json (keep-rate, per-language counts, score hist, drop reasons) and a
--samples file with KEPT+DROPPED examples per a few languages for human inspection.

    python scripts/data/filter_code_quality.py \
        --input raw/code/starcoderdata.txt \
        --output cleaned/code/starcoder_multi.edu.txt \
        --threshold 3 --samples diag/starcoder_edu_samples.txt
"""
from __future__ import annotations
import argparse, ast, json, re, time
from pathlib import Path

BEGIN = "<|code|>"
END = "<|endcode|>"
FILENAME = "<filename>"
TAG = re.compile(r"^<\|code\|>\[([a-zA-Z0-9+#._-]+)\]")
AUTOGEN = re.compile(r"(@generated|do not edit|autogenerated|automatically generated|"
                     r"this file was generated|code generated by|do not modify)", re.I)
# vendored / lockfile / minified-by-name: never useful training signal
VENDORED_PATH = re.compile(r"(^|/)(node_modules|vendor|third_party|bower_components)/|"
                           r"\.min\.(js|css)$|(^|/)(package-lock\.json|yarn\.lock|Cargo\.lock|"
                           r"poetry\.lock|composer\.lock|Pipfile\.lock)$|"
                           r"_pb2(_grpc)?\.py$|\.pb\.(go|cc|h)$|\.bundle\.js$", re.I)
# language-agnostic structural tokens (control flow / definitions across the 9 langs)
CODE_KW = re.compile(r"\b(def|class|return|import|from|require|module|func|fn|function|"
                     r"public|private|protected|static|void|const|let|var|struct|enum|"
                     r"impl|trait|package|interface|select|insert|update|delete|where|"
                     r"if|else|elif|for|while|switch|case|try|catch|except|async|await)\b",
                     re.I)
COMMENT_PREFIX = ("#", "//", "--", "/*", "*", "<!--")


def looks_like_comment(ln: str) -> bool:
    s = ln.lstrip()
    return any(s.startswith(p) for p in COMMENT_PREFIX)


def analyze(code: str, lang: str, threshold: int, filename: str = "") -> tuple[bool, int, str]:
    lines = code.split("\n")
    nonblank = [ln for ln in lines if ln.strip()]
    if len(nonblank) < 4:
        return False, 0, "too_short"
    if filename and VENDORED_PATH.search(filename):
        return False, 0, "vendored_path"
    # Scan HEAD and TAIL (not just the first 4000 chars: long license headers push
    # the marker past the old window, and many generators stamp the END of file).
    # Mid-file hits are skipped on purpose — those are usually code-generator
    # templates, i.e. legitimate hand-written code.
    if AUTOGEN.search(code[:8000]) or (len(code) > 8000 and AUTOGEN.search(code[-2000:])):
        return False, 0, "autogenerated"

    parse_ok = None
    if lang == "python":
        try:
            ast.parse(code)
            parse_ok = True
        except (SyntaxError, ValueError):
            return False, 0, "parse_fail"      # HARD gate: only valid py3

    comment_lines = [ln for ln in nonblank if looks_like_comment(ln)]
    code_lines = [ln for ln in nonblank if not looks_like_comment(ln)]
    max_len = max((len(ln) for ln in lines), default=0)
    avg_len = sum(len(ln) for ln in code_lines) / max(1, len(code_lines))
    ascii_ratio = sum(1 for c in code if ord(c) < 128) / max(1, len(code))
    doc_ratio = len(comment_lines) / max(1, len(nonblank))
    kw_hits = len(CODE_KW.findall(code))

    # minified / data-dump rejects (mostly hits JS/JSON/lockfiles)
    if max_len > 1000 or avg_len > 200:
        return False, 0, "minified"
    if kw_hits < 3:
        return False, 0, "no_code_structure"   # JSON/data dump, not real code

    score = 0
    if parse_ok or lang != "python":
        score += 1                                              # passes language gate
    if kw_hits >= 5:
        score += 1                                              # real structure/logic
    if doc_ratio >= 0.04:
        score += 1                                              # documented
    if max_len <= 200 and avg_len <= 100:
        score += 1                                              # clean formatting
    if 8 <= len(code_lines) <= 1200 and ascii_ratio >= 0.92:
        score += 1                                              # substantial + clean
    keep = score >= threshold
    return keep, score, ("kept" if keep else "low_score")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--threshold", type=int, default=3)
    ap.add_argument("--langs", default="", help="comma list to keep; empty = all languages")
    ap.add_argument("--samples", type=Path, default=None)
    ap.add_argument("--sample-n", type=int, default=20)
    ap.add_argument("--limit", type=int, default=0)
    a = ap.parse_args()
    keep_langs = set(x.strip() for x in a.langs.split(",") if x.strip())

    a.output.parent.mkdir(parents=True, exist_ok=True)
    hist = {s: 0 for s in range(6)}
    drops: dict[str, int] = {}
    per_lang_seen: dict[str, int] = {}
    per_lang_kept: dict[str, int] = {}
    files = kept = 0
    bytes_kept = 0
    t0 = time.monotonic()
    samples: list[str] = []

    out = a.output.open("w", encoding="utf-8")
    buf: list[str] = []
    in_block = False

    def handle(block_lines: list[str]) -> bool:
        nonlocal files, kept, bytes_kept
        if not block_lines:
            return True
        files += 1
        m = TAG.match(block_lines[0])
        lang = m.group(1).lower() if m else "unknown"
        per_lang_seen[lang] = per_lang_seen.get(lang, 0) + 1
        if keep_langs and lang not in keep_langs:
            drops["lang_excluded"] = drops.get("lang_excluded", 0) + 1
            return True
        body = [ln for ln in block_lines
                if not ln.startswith(BEGIN) and not ln.startswith(FILENAME) and ln.strip() != END]
        code = "\n".join(body)
        fname = next((ln[len(FILENAME):].strip() for ln in block_lines if ln.startswith(FILENAME)), "")
        keep, score, reason = analyze(code, lang, a.threshold, filename=fname)
        hist[score] = hist.get(score, 0) + 1
        if keep:
            block = "\n".join(block_lines)
            out.write(block + "\n")
            kept += 1
            bytes_kept += len(block.encode("utf-8")) + 1
            per_lang_kept[lang] = per_lang_kept.get(lang, 0) + 1
            if a.samples and len(samples) < a.sample_n:
                samples.append(f"--- KEPT [{lang}] score={score} ---\n{code[:600]}")
        else:
            drops[reason] = drops.get(reason, 0) + 1
        return not (a.limit and files >= a.limit)

    with a.input.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            s = line.rstrip("\n")
            if s.startswith(BEGIN):
                if in_block and not handle(buf):
                    buf = []
                    break
                buf = [s]
                in_block = True
            elif in_block:
                buf.append(s)
                if s.strip() == END:
                    cont = handle(buf)
                    buf = []
                    in_block = False
                    if not cont:
                        break
            if files and files % 100000 == 0 and not in_block:
                rate = files / max(1e-9, time.monotonic() - t0)
                print(f"  files {files:,} | kept {kept:,} ({100*kept/max(1,files):.1f}%) | {rate:.0f}/s", flush=True)
        if buf:
            handle(buf)
    out.close()

    manifest = {
        "input": str(a.input), "output": str(a.output), "threshold": a.threshold,
        "files": files, "kept": kept, "keep_rate": round(kept / max(1, files), 4),
        "approx_tokens_kept_B": round(bytes_kept / 2.85 / 1e9, 3),
        "per_language_seen": dict(sorted(per_lang_seen.items(), key=lambda x: -x[1])),
        "per_language_kept": dict(sorted(per_lang_kept.items(), key=lambda x: -x[1])),
        "score_hist": hist, "drop_reasons": drops, "elapsed_s": round(time.monotonic() - t0, 1),
    }
    a.output.with_suffix(a.output.suffix + ".manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    if a.samples:
        a.samples.parent.mkdir(parents=True, exist_ok=True)
        a.samples.write_text("\n\n".join(samples), encoding="utf-8")
    print("\n=== multilingual code-quality filter ===")
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    print(f"wrote {a.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
